@echo off
setlocal enabledelayedexpansion

:: ─── Voicer Installer Build Script ──────────────────────────────────────────
:: Downloads embedded Python, installs deps, copies host files, compiles .exe
:: Run from: installer\ directory

set PYTHON_VERSION=3.12.8
set PYTHON_ZIP=python-%PYTHON_VERSION%-embed-amd64.zip
set PYTHON_URL=https://www.python.org/ftp/python/%PYTHON_VERSION%/%PYTHON_ZIP%
set GETPIP_URL=https://bootstrap.pypa.io/get-pip.py
set BUNDLE=bundle
set ISCC="%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe"

:: ─── Read config from host/.env (never hardcoded in source) ─────────────────
set SUPABASE_SRK=
for /f "tokens=1,* delims==" %%a in ('findstr /b "SUPABASE_SERVICE_ROLE_KEY" "..\host\.env"') do set SUPABASE_SRK=%%b
if "%SUPABASE_SRK%"=="" (
    echo ERROR: SUPABASE_SERVICE_ROLE_KEY not found in host\.env
    echo        The build reads this key from your local .env file.
    exit /b 1
)
set SUPABASE_URL=
for /f "tokens=1,* delims==" %%a in ('findstr /b "SUPABASE_URL" "..\host\.env"') do set SUPABASE_URL=%%b
if "%SUPABASE_URL%"=="" (
    echo ERROR: SUPABASE_URL not found in host\.env
    exit /b 1
)

echo ═══════════════════════════════════════════
echo   Voicer Installer Build
echo ═══════════════════════════════════════════

:: ─── Step 1: Clean previous build ───────────────────────────────────────────
echo.
echo [1/6] Cleaning previous build...
if exist "%BUNDLE%\python" rmdir /s /q "%BUNDLE%\python"
if exist "%BUNDLE%\host" rmdir /s /q "%BUNDLE%\host"
mkdir "%BUNDLE%\python" 2>nul
mkdir "%BUNDLE%\host" 2>nul

:: ─── Step 2: Download embedded Python ───────────────────────────────────────
echo [2/6] Downloading Python %PYTHON_VERSION% embeddable...
if not exist "%PYTHON_ZIP%" (
    curl -L -o "%PYTHON_ZIP%" "%PYTHON_URL%"
    if errorlevel 1 (
        echo ERROR: Failed to download Python. Check your internet connection.
        exit /b 1
    )
)
echo Extracting...
powershell -Command "Expand-Archive -Force '%PYTHON_ZIP%' '%BUNDLE%\python'"

:: ─── Step 3: Enable pip in embedded Python ──────────────────────────────────
echo [3/6] Setting up pip...

:: Uncomment "import site" in python312._pth so pip/packages work
set PTH_FILE=%BUNDLE%\python\python312._pth
powershell -Command "(Get-Content '%PTH_FILE%') -replace '^#import site','import site' | Set-Content '%PTH_FILE%'"

:: Download and run get-pip.py
if not exist "get-pip.py" (
    curl -L -o get-pip.py "%GETPIP_URL%"
)
"%BUNDLE%\python\python.exe" get-pip.py --no-warn-script-location
if errorlevel 1 (
    echo ERROR: pip installation failed.
    exit /b 1
)

:: ─── Step 4: Install requirements ───────────────────────────────────────────
echo [4/6] Installing Python dependencies (this may take a minute)...
"%BUNDLE%\python\python.exe" -m pip install -r "..\host\requirements.txt" --no-warn-script-location -q
if errorlevel 1 (
    echo ERROR: Failed to install requirements.
    exit /b 1
)

:: ─── Step 5: Copy host files ────────────────────────────────────────────────
echo [5/6] Copying host files...
for %%f in (server.py webrtc_host.py screen.py input.py gemini_live.py supabase_client.py requirements.txt) do (
    copy /y "..\host\%%f" "%BUNDLE%\host\%%f" >nul 2>&1
)

:: .env template — service role key baked from local host/.env at build time.
:: USER_ID and GEMINI_API_KEY are filled by installer or activation flow.
(
    echo # Voicer Desktop Host Configuration
    echo # Generated by Voicer Installer
    echo.
    echo SUPABASE_URL=!SUPABASE_URL!
    echo SUPABASE_SERVICE_ROLE_KEY=!SUPABASE_SRK!
    echo USER_ID=
    echo GEMINI_API_KEY=
    echo USE_HOSTED_API=false
) > "%BUNDLE%\host\.env.template"

:: Copy start script
copy /y "start_voicer.bat" "%BUNDLE%\start_voicer.bat" >nul

:: ─── Step 6: Compile installer ──────────────────────────────────────────────
echo [6/6] Compiling installer with Inno Setup...
%ISCC% voicer.iss
if errorlevel 1 (
    echo ERROR: Inno Setup compilation failed.
    exit /b 1
)

echo.
echo ═══════════════════════════════════════════
echo   BUILD COMPLETE
echo   Output: Output\VoicerSetup.exe
echo ═══════════════════════════════════════════
pause
